version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-npm-updates:
        patterns:
          - "*"
    labels: ["deps", "auto-update"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-pip-updates:
        patterns:
          - "*"
    labels: ["deps", "auto-update"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions-updates:
        patterns:
          - "*"
    labels: ["deps", "ci"]
